# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

git:
  log:
    # for other options, press <c-l> in commit view, to change stuff eg. sort order to date-order instead of topo-order
    showWholeGraph: true

